### ISSUE TITLE
Negative Duration

### ISSUE THREAD

**Issue by solodkiy** [brick/date-time#72]
Right now value in Duration object could be negative. (-1 sec)

I don't really get this concept (negative duration, negative distance etc). Could you, please, give some examples when negative Duration is really helps?

**Comment by gnutix** [comment]
We use this in our application for the following example : an employee should come to work from 8 am to 17 pm. That's a `Duration::ofHours(9)`. Yet the employee is expected to follow the work laws and have at least one hour of break during that day. As we sometimes don't know when the employee will take it and can't plan for it, we have a `Duration::ofHours(-1)` adjustment that is applied afterwards so that the day's work duration is `Duration::ofHours(8)` (as is expected of the employee).

Hope this helps.

**Comment by BenMorel** [comment]
Thanks for providing a use case, @gnutix!

Plus, the [upstream Java implementation](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html) also allows negative durations, so I think it's fine as it is.
