### ISSUE TITLE
Consider adding equals() method to all value classes

### ISSUE THREAD

**Issue by joshdifabio** [brick/date-time#9]
An equals($value) method on all value classes (no type declaration on the parameter) would make this library much easier to work with in combination with other libraries which deal with generic value types, e.g. https://github.com/Space48/auto-value-php.

**Comment by BenMorel** [comment]
I'm closing this issue due to lack of feedback.

As mentioned above, most classes implement an `isEqualTo()` method, that compares to objects of the same type. I currently don't see a value in comparing to objects of other types, if that's what the issue is about.

Please feel free to comment if you wish to reopen the discussion.
